export const ADD_NEW_WORD = 'ADD_NEW_WORD';
export const RECEIVE_NEW_WORD = 'RECEIVE_NEW_WORD';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const WORD_EXISTED_ERROR = 'WORD_EXISTED_ERROR';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const FETCH_WORD_DATA = 'FETCH_WORD_DATA';
